Fix NPE when removing a workflow without creator
If a workflow has no creator (maybe because the user has been removed),
removing a workflow fails with a NullPointerException when Opencast
tries loading details of the user `null`.

```
2023-09-05 13:08:19,950 | ERROR | (AbstractScanner$TypedQuartzJob$1:314) - An error occurred while harvesting schedule
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[?:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[?:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[?:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[?:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[?:?]
        at org.opencastproject.userdirectory.UserAndRoleDirectoryServiceImpl.loadUser(UserAndRoleDirectoryServiceImpl.java:265) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.assertPermission(WorkflowServiceImpl.java:1132) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.getWorkflowById(WorkflowServiceImpl.java:446) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:928) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:914) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.cleanupWorkflowInstances(WorkflowServiceImpl.java:2125) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner.scan(WorkflowCleanupScanner.java:203) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner$Runner.execute(WorkflowCleanupScanner.java:266) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner$Runner.execute(WorkflowCleanupScanner.java:252) ~[?:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob$1.xapply(AbstractScanner.java:311) ~[?:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob$1.xapply(AbstractScanner.java:307) ~[?:?]
        at org.opencastproject.util.data.Function0$X.apply(Function0.java:53) ~[?:?]
        at org.opencastproject.util.NeedleEye.apply(NeedleEye.java:46) ~[?:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob.execute(AbstractScanner.java:297) ~[?:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216) ~[?:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[?:?]
Caused by: java.lang.NullPointerException
        at org.opencastproject.userdirectory.JpaUserAndRoleProvider.loadUser(JpaUserAndRoleProvider.java:252) ~[?:?]
        at org.opencastproject.userdirectory.UserAndRoleDirectoryServiceImpl.loadUser(UserAndRoleDirectoryServiceImpl.java:310) ~[?:?]
        at org.opencastproject.userdirectory.UserAndRoleDirectoryServiceImpl$1.load(UserAndRoleDirectoryServiceImpl.java:115) ~[?:?]
        at org.opencastproject.userdirectory.UserAndRoleDirectoryServiceImpl$1.load(UserAndRoleDirectoryServiceImpl.java:112) ~[?:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[?:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[?:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[?:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[?:?]
        ... 23 more
```

This patch fixes the problem.