Fix adopter statistic breaking on non-set metadata
The duration metadata field is not required for publication and therefor
may not exists. This can lead to NullPointerExceptions when trying to
generate the adopter statistics data.

```
2025-03-23T23:18:50,747 | ERROR | (ScheduledDataCollector:235) - Error occurred while processing adopter statistic data.
java.lang.NullPointerException: Cannot invoke "String.regionMatches(boolean, int, String, int, int)" because "<parameter2>" is null
        at org.joda.time.format.PeriodFormatterBuilder$Literal.parseInto(PeriodFormatterBuilder.java:1906) ~[!/:2.12.7]
        at org.joda.time.format.PeriodFormatterBuilder$Composite.parseInto(PeriodFormatterBuilder.java:2171) ~[!/:2.12.7]
        at org.joda.time.format.PeriodFormatterBuilder$Separator.parseInto(PeriodFormatterBuilder.java:2044) ~[!/:2.12.7]
        at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:323) ~[!/:2.12.7]
        at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:309) ~[!/:2.12.7]
        at org.opencastproject.metadata.dublincore.EncodingSchemeUtils.decodeDuration(EncodingSchemeUtils.java:158) ~[!/:?]
        at org.opencastproject.adopter.statistic.ScheduledDataCollector.lambda$collectStatisticData$2(ScheduledDataCollector.java:309) ~[!/:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at org.opencastproject.adopter.statistic.ScheduledDataCollector.lambda$collectStatisticData$3(ScheduledDataCollector.java:312) ~[!/:?]
        at org.opencastproject.security.util.SecurityUtil.runAs(SecurityUtil.java:80) ~[!/:?]
        at org.opencastproject.adopter.statistic.ScheduledDataCollector.collectStatisticData(ScheduledDataCollector.java:294) ~[!/:?]
        at org.opencastproject.adopter.statistic.ScheduledDataCollector.run(ScheduledDataCollector.java:230) [!/:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
```

This patch fixes the issue, so that adopter statistics are again sent to
the registration server if the user opted in.