Fix `jakarta.mail` Dependency Problem
In the new CXF version, `javax.mail` has been replaced by
`jakarta.mail-api` whis was missing in our distributions.
This caused a broken mail system in Opencast and an exception on boot:

```
2021-06-17 19:23:34,228 | ERROR | (Log:186) - [org.osgi.service.cm.ManagedService, org.opencastproject.kernel.mail.SmtpService, id=396, bundle=134/mvn:org.opencastproject/opencast-kernel/10.0]: Unexpected problem updating configuration org.opencastproject.kernel.mail.SmtpService
java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
	at javax.mail.Session.initLogger(Session.java:260) ~[?:?]
        ...
```

This patch adds the latest 1.6 version of `jakarta.mail-api`.
This fixes #2746.