Fix Solr Metadata Field
Pull request #2815 (commit 5520156) fixed an issue with the publication
of metadata with different language tags. Unfortunately, the patch used
the empty string to represent all metadata values. This conflicts with
the most commonly used one for representing data with no language tags
which was `__`.

This results in a conflict if people now republish media which were
previously published using a different language representation.

This patch switches back to `__` to avoid further conflicts.

Unfortunately, these changes make a search service Solr index rebuild
necessary in _some_ cases. Other Solr or Elasticsearch indexes are _not_
effected in any way.

Who is effected and what's the effect
-------------------------------------

__If you have never run Opencast 10.1__:

Don't worry. No action is necessary. Just upgrade from Opencast ≤ 9.x to
Opencast ≥ 10.2 directly.

__If you did run Opencast 10.1 in production__

You may already have seen an error message like this while trying to
republish media originally published with Opencast ≤ Opencast 10.0:

    (SolrException:139) - org.apache.solr.common.SolrException:
       ERROR: multiple values encountered for non multiValued
       copy field dc_title-sort

This happens if old and new data get mixed. The field `dc_title-sort`
will automatically gather multiple values but can actually only handle a
single value. Hence, (re-)publication will fail.

To fix this, you will need to re-write the Solr entries set in 10.1,
either by removing and resetting specific events or (recommended) by
re-indexing all events.

To re-index, stop Opencast, remove `<karaf-data>/solr-indexes/search`
and restart Opencast. The re-index progress will be logged. Fortunately,
this is a lot faster than with Elasticsearch.

_Sorry for the inconvenience!_