Don't fail theme index rebuild if user does not exist
If the user who created a theme does no longer exist, the index rebuild
will fail with a NullPointerException. This patch fixes the problem by
providing an empty string instead.

```
2025-03-18T11:35:30,113 | ERROR | (AbstractIndexProducer:186) - Error updating the Themes index.
java.lang.NullPointerException: Cannot invoke "org.opencastproject.security.api.User.getName()" because the return value of "org.opencastproject.themes.Theme.getCreator()" is null
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.lambda$getThemeUpdateFunction$9(ThemesServiceDatabaseImpl.java:426) ~[?:?]
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:316) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndexInternal(IndexRebuildService.java:213) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:158) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$5(IndexEndpoint.java:240) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$6(IndexEndpoint.java:237) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
2025-03-18T11:35:30,113 | ERROR | (IndexEndpoint:242) - Repopulating the index failed
org.opencastproject.elasticsearch.index.rebuild.IndexRebuildException: Error updating the index for service Themes
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:332) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndexInternal(IndexRebuildService.java:213) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:158) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$5(IndexEndpoint.java:240) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$6(IndexEndpoint.java:237) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.opencastproject.security.api.User.getName()" because the return value of "org.opencastproject.themes.Theme.getCreator()" is null
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.lambda$getThemeUpdateFunction$9(ThemesServiceDatabaseImpl.java:426) ~[?:?]
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:316) ~[?:?]
        ... 10 more
```